Update README.md
saikou-app/saikou pull request #476
Opened 2022-12-08 09:03 UTC by SunglassJerry

Updated Sources and Planned Stuff

2022-12-08 09:05 UTC, scrazzz requested changes

2022-12-08 09:05 UTC, scrazzz commented on README.md
> +| [Toonily (18+)](https://toonily.com/)         | WORKING |
```suggestion
| [Toonily](https://toonily.com/)         | WORKING |
```
Toonily isn't an NSFW source

2022-12-08 09:08 UTC, SunglassJerry commented on README.md
> +| [Toonily (18+)](https://toonily.com/)         | WORKING |
But it does contain a lot of nsfw. A comparatively small portion is non-nsfw. I explored the site for 3 minutes before updating it

2022-12-08 09:10 UTC, SunglassJerry commented on README.md
> +| [Toonily (18+)](https://toonily.com/)         | WORKING |
That's why I think it's better if we mark it nsfw. But can be accessed for normal mangas in the app.

2022-12-08 09:11 UTC, SunglassJerry commented on README.md
> +| [Toonily (18+)](https://toonily.com/)         | WORKING |
If you still don't want it to be like that. Then ok...

2022-12-08 09:17 UTC, scrazzz commented on README.md
>  | [Kamyroll](https://kamyroll.herokuapp.com)| WORKING | NO   |
```suggestion
| [Kamyroll](https://github.com/kamyroll/Kamyroll-Wiki/wiki)| WORKING | NO   |
```

2022-12-08 09:18 UTC, scrazzz requested changes

2022-12-08 09:18 UTC, scrazzz commented on README.md
>  | [Kamyroll](https://kamyroll.herokuapp.com)| WORKING | NO   |
```suggestion
| [Kamyroll](https://github.com/kamyroll/Kamyroll-Wiki/wiki)| WORKING | NO   |
```

2022-12-08 09:20 UTC, scrazzz approved these changes

2022-12-08 09:20 UTC, scrazzz commented
LGTM

2022-12-08 09:21 UTC, merged

2022-12-13 01:09 UTC, Dawson908 commented
@scrazzz app having problem

2022-12-13 01:10 UTC, Dawson908 commented on README.md
>  | [Kamyroll](https://kamyroll.herokuapp.com)| WORKING | NO   |
Need some new sources on the app