fix(KAA): fix KAA
saikou-app/saikou pull request #550
Opened 2023-02-15 13:38 UTC by TobyBridle

This might take a little while since I have a very important project due but shouldn't be too long.
I have added the Sapphire Duck extractor as a I'm pretty certain that it's ready but I'll be able to tell once I have the rest of the code working.

2023-02-15 19:22 UTC, TobyBridle commented
I'm going to **try** and hold off on working on this for a bit, as it seems that KAA are in the process of upgrading their API.
They've just updated their `episodes` route and added a seasons route which I have accounted for but a lot of things are still returning empty objects.

2023-02-28 20:33 UTC, scrazzz commented on app/src/main/java/ani/saikou/parsers/AnimeSources.kt
> +        "KickAssAnime" to ::KickAssAnime
```suggestion
        "KickAssAnime" to ::KickAssAnime,
```

2023-02-28 20:35 UTC, scrazzz commented on app/src/main/java/ani/saikou/parsers/AnimeSources.kt
> +        "KickAssAnime" to ::KickAssAnime
```suggestion
        "KickAssAnime" to ::KickAssAnime,
```

2023-02-28 20:37 UTC, scrazzz commented on app/src/main/java/ani/saikou/parsers/anime/KickAssAnime.kt
> +import com.lagradost.nicehttp.JsonAsString
We don't use lagradost's nicehttp anymore, it was removed on [this commit](https://github.com/saikou-app/saikou/commit/4a3fcc3b36363ac0d994e83d609266b078c4e9ce)

2023-02-28 20:40 UTC, scrazzz commented on app/src/main/java/ani/saikou/parsers/anime/KickAssAnime.kt
> +  val thumbnailUrl = "$hostUrl/images/thumbnail"
These `val`s could be made private.

2023-02-28 20:43 UTC, scrazzz reviewed
Everything else looks good. Just needs some minor changes.

Ask Shivam about the nicehttp `JsonAsString()` method. I don't see that method on Shivam's new nicehttp library.

2023-03-02 13:00 UTC, scrazzz requested changes

2023-03-02 13:01 UTC, scrazzz commented on app/src/main/java/ani/saikou/parsers/anime/KickAssAnime.kt
> +        val pageEpisodes = client.get("$url&page=$page", headers = mapOf("accept" to "application/json")).parsed<EpisodesJSON>().episodes;
Same here

2023-03-02 14:15 UTC, scrazzz approved these changes

2023-03-02 14:16 UTC, merged