feat: add mangokomi source
saikou-app/saikou pull request #645
Opened 2023-04-13 15:39 UTC by justchokingaround

#414

2023-04-13 15:39 UTC, justchokingaround commented
first time coding in kotlin :flushed:

2023-04-13 15:44 UTC, Adolar0042 commented on app/src/main/res/layout/item_anime_page.xml
> +                    android:id="@+id/genres"
why the added id?

2023-04-13 15:46 UTC, Adolar0042 reviewed
lgtm

2023-04-14 10:56 UTC, justchokingaround commented on app/src/main/res/layout/item_anime_page.xml
> +</LinearLayout>
i have no idea why this happens, it's the same file as main

2023-04-14 10:57 UTC, justchokingaround commented on app/src/main/java/ani/saikou/parsers/manga/MangaKomi.kt
> +            MangaChapter(number = chapNumRe.find(it.text())?.groupValues?.get(1).toString(), link = it.attr("href"))
i think i fixed this, not sure if that's what you wanted?

2023-04-14 15:53 UTC, brahmkshatriya requested changes

2023-04-14 15:53 UTC, brahmkshatriya commented on app/src/main/java/ani/saikou/parsers/manga/MangaKomi.kt
> +                MangaChapter(number = matchResult.groupValues[1], link = it.attr("href"))
a better way to do this would be
```kotlin
val number = chapNumRe.find(it.text())?.matchResult?.groupValues[1] ?: return@mapNotNull null
MangaChapter(number,it.attr("href"))
 ```

2023-04-14 16:41 UTC, justchokingaround commented on app/src/main/java/ani/saikou/parsers/manga/MangaKomi.kt
> +                MangaChapter(number = matchResult.groupValues[1], link = it.attr("href"))
should be good to go now

2023-04-14 19:44 UTC, merged